# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: centry
    binary: "{{ .ProjectName }}_{{ .Tag }}"
    goos:
      - darwin
      - linux
    goarch:
      - "386"
      - "amd64"
      - "arm64"
    env:
      - CGO_ENABLED=0
archives:
  - id: centry
    builds:
      - centry
    replacements:
      darwin: Darwin
      linux: Linux
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^.github:"
      - "^docs:"
      - "^examples:"
      - "^scripts:"
      - "^test:"
