#!/usr/bin/env bash

declare gobindata
gobindata="$(which go-bindata)"

if ! "${gobindata}" -v &>/dev/null; then
  gobindata='./go-bindata'
  curl --silent --location --output "${gobindata:?}" https://github.com/kevinburke/go-bindata/releases/download/v3.22.0/go-bindata-linux-amd64
  chmod 755 "${gobindata:?}"
fi

"${gobindata:?}" -pkg config -o internal/pkg/config/schema.go schemas/manifest.json
